---
- name: install sniproxy firewall rules
  iptables_raw:
    name: sniproxy_rules
    weight: 10
    keep_unmanaged: no
    rules: |
      -A INPUT -i {{ ansible_default_ipv4.interface }} -s {{ item }} -p tcp -m multiport --dports 80,443 -j ACCEPT
  with_lines: cat "{{ playbook_dir }}/environments/{{ env }}/files/ip_whitelist.txt"  
  notify:
  - save iptables
  tags: sniproxy
