---
- name: flush firewall rules (IPv6)
  iptables_raw:
    name: '*'
    table: '*'
    ipversion: 6
    state: absent
  notify:
  - save ip6tables
  tags: ip6tables

- name: install default firewall rules (IPv6)
  iptables_raw:
    name: default_rules
    ipversion: 6
    keep_unmanaged: no
    rules: |
      -A INPUT -p ipv6-icmp -j ACCEPT
      -A INPUT -i lo -j ACCEPT
      -A INPUT -p tcp -m state --state NEW -m tcp --dport 22 -j ACCEPT
      -A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
      -A INPUT -j REJECT --reject-with icmp6-adm-prohibited
  notify:
  - save ip6tables
  tags: ip6tables
