---
- name: flush firewall rules
  iptables_raw:
    name: '*'
    table: '*'
    state: absent
  notify:
  - save iptables
  tags: iptables

- name: install default firewall rules
  iptables_raw:
    name: default_rules
    keep_unmanaged: no
    rules: |
      -A INPUT -p icmp -j ACCEPT
      -A INPUT -i lo -j ACCEPT
      -A INPUT -p tcp -m state --state NEW -m tcp --dport 22 -j ACCEPT
      -A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
      -A INPUT -j REJECT --reject-with icmp-host-prohibited
  notify:
  - save iptables
  tags: iptables
